name: HypixelSkyblock
version: ${project.version}
main: me.cyberdie22.hypixelskyblock.HypixelSkyblock
api-version: 1.16
load: STARTUP
authors: [ CyberDie22 ]
description: Recreation of Hypixel Skyblock
commands:
  hypixelskyblock:
    description: Main command for HypixelSkyblock. Use /template help for more info
permissions:
  hypixelskyblock.user:
    description: Allows player to use the plugin's user features
    default: true
  hypixelskyblock.admin:
    description: Allows player to use the plugin's admin features
    default: op
